export const DINOS = [

	{
		name: 'name_amar',
		category: 'non volant',
		id: 'amar',
		price: 3200,
		neutedPrice: 1100,
		nameStat1: 'stat_health',
		nameStat2: 'stat_dmg',
		nameStat3: 'stat_stam',
		nameStat4: 'stat_weight'
	},
	{
		name: 'name_andrew',
		category: 'non volant',
		id: 'andrew',
		price: 3200,
		neutedPrice: 1100,
		nameStat1: 'stat_health',
		nameStat2: 'stat_dmg',
		nameStat3: 'stat_stam',
		nameStat4: 'stat_weight'
	},
	{
		name: 'name_ankylo',
		category: 'non volant',
		id: 'ankylo',
		price: 6500,
		neutedPrice: 2100,
		nameStat1: 'stat_dmg',
		nameStat2: '',
		nameStat3: '',
		nameStat4: ''
	},
	{
		name: 'name_argent',
		category: 'volant',
		id: 'argent',
		price: 3200,
		neutedPrice: 1300,
		nameStat1: 'stat_weight',
		nameStat2: 'stat_stam',
		nameStat3: 'stat_dmg',
		nameStat4: 'stat_health'
	},
	{
		name: 'name_astrodel',
		category: 'volant',
		id: 'astrodel',
		price: 5200,
		neutedPrice: 1900,
		nameStat1: 'stat_health',
		nameStat2: 'stat_weight',
		nameStat3: 'stat_stam',
		nameStat4: 'stat_dmg'
	},
	{
		name: 'name_basilisk',
		category: 'non volant',
		id: 'basilisk',
		price: 7800,
		neutedPrice: 2600,
		nameStat1: 'stat_dmg',
		nameStat2: 'stat_stam',
		nameStat3: 'stat_health',
		nameStat4: 'stat_weight'
	},
	{
		name: 'name_basilo',
		category: 'non volant',
		id: 'basilo',
		price: 6300,
		neutedPrice: 2100,
		nameStat1: 'stat_dmg',
		nameStat2: 'stat_health',
		nameStat3: 'stat_stam',
		nameStat4: 'stat_weight'
	},
	{
		name: 'name_beelzebufo',
		category: 'non volant',
		id: 'beelzebufo',
		price: 3200,
		neutedPrice: 1100,
		nameStat1: 'stat_dmg',
		nameStat2: 'stat_weight',
		nameStat3: '',
		nameStat4: ''
	},
	{
		name: 'name_blood',
		category: 'non volant',
		id: 'blood',
		price: 5200,
		neutedPrice: 1900,
		nameStat1: 'stat_health',
		nameStat2: 'stat_weight',
		nameStat3: 'stat_stam',
		nameStat4: 'stat_dmg'
	},
	{
		name: 'name_bronto',
		category: 'non volant',
		id: 'bronto',
		price: 4700,
		neutedPrice: 1600,
		nameStat1: 'stat_dmg',
		nameStat2: 'stat_weight',
		nameStat3: '',
		nameStat4: ''
	},
	{
		name: 'name_castor',
		category: 'non volant',
		id: 'castor',
		price: 6300,
		neutedPrice: 2100,
		nameStat1: 'stat_dmg',
		nameStat2: 'stat_weight',
		nameStat3: '',
		nameStat4: ''
	},
	{
		name: 'name_carcha',
		category: 'non volant',
		id: 'carcha',
		price: 13000,
		neutedPrice: 5200,
		nameStat1: 'stat_dmg',
		nameStat2: '',
		nameStat3: '',
		nameStat4: ''
	},
	{
		name: 'name_daeodon',
		category: 'non volant',
		id: 'daeodon',
		price: 4700,
		neutedPrice: 1600,
		nameStat1: 'stat_food',
		nameStat2: 'stat_health',
		nameStat3: '',
		nameStat4: ''
	},
	{
		name: 'name_deino',
		category: 'non volant',
		id: 'deino',
		price: 3200,
		neutedPrice: 1100,
		nameStat1: 'stat_health',
		nameStat2: 'stat_dmg',
		nameStat3: 'stat_stam',
		nameStat4: 'stat_weight'
	},
	{
		name: 'name_deod',
		category: 'non volant',
		id: 'doed',
		price: 6500,
		neutedPrice: 2100,
		nameStat1: 'stat_dmg',
		nameStat2: '',
		nameStat3: '',
		nameStat4: ''
	},
	{
		name: 'name_desmo',
		category: 'volant',
		id: 'desmo',
		price: 5200,
		neutedPrice: 1900,
		nameStat1: 'stat_health',
		nameStat2: 'stat_weight',
		nameStat3: 'stat_stam',
		nameStat4: 'stat_dmg'
	},
	{
		name: 'name_dinopi',
		category: 'non volant',
		id: 'dinopi',
		price: 3900,
		neutedPrice: 1300,
		nameStat1: 'stat_dmg',
		nameStat2: 'stat_health',
		nameStat3: 'stat_stam',
		nameStat4: 'stat_weight'
	},
	{
		name: 'name_dunkleo',
		category: 'non volant',
		id: 'dunkleo',
		price: 3200,
		neutedPrice: 1100,
		nameStat1: 'stat_dmg',
		nameStat2: 'stat_weight',
		nameStat3: '',
		nameStat4: ''
	},
	{
		name: 'name_ferox',
		category: 'non volant',
		id: 'ferox',
		price: 9400,
		neutedPrice: 3900,
		nameStat1: 'stat_dmg',
		nameStat2: 'stat_stam',
		nameStat3: 'stat_health',
		nameStat4: 'stat_weight'
	},
	{
		name: 'name_fjord',
		category: 'non volant',
		id: 'fjord',
		price: 3200,
		neutedPrice: 1300,
		nameStat1: 'stat_weight',
		nameStat2: 'stat_stam',
		nameStat3: 'stat_dmg',
		nameStat4: 'stat_health'
	},
	{
		name: 'name_gacha_ele',
		category: 'non volant',
		id: 'gacha_ele',
		price: 2100,
		nameStat1: '',
		nameStat2: '',
		nameStat3: '',
		nameStat4: ''
	},
	{
		name: 'name_gacha_black',
		category: 'non volant',
		id: 'gacha_black',
		price: 1600,
		nameStat1: '',
		nameStat2: '',
		nameStat3: '',
		nameStat4: ''
	},
	{
		name: 'name_gacha_other',
		category: 'non volant',
		id: 'gacha',
		price: 1000,
		nameStat1: '',
		nameStat2: '',
		nameStat3: '',
		nameStat4: ''
	},
	{
		name: 'name_gasbag',
		category: 'non volant',
		id: 'gasbag',
		price: 3200,
		neutedPrice: 1100,
		nameStat1: 'stat_oxy',
		nameStat2: 'stat_weight',
		nameStat3: 'stat_stam',
		nameStat4: ''
	},
	{
		name: 'name_gigano',
		category: 'non volant',
		id: 'gigano',
		price: 13000,
		neutedPrice: 5200,
		nameStat1: 'stat_dmg',
		nameStat2: '',
		nameStat3: '',
		nameStat4: ''
	},
	{
		name: 'name_griffin',
		category: 'volant',
		id: 'griffin',
		price: 4700,
		neutedPrice: 1600,
		nameStat1: 'stat_weight',
		nameStat2: 'stat_stam',
		nameStat3: 'stat_dmg',
		nameStat4: 'stat_health'
	},
	{
		name: 'name_owl',
		category: 'volant',
		id: 'owl',
		price: 3900,
		neutedPrice: 1300,
		nameStat1: 'stat_health',
		nameStat2: 'stat_stam',
		nameStat3: '',
		nameStat4: ''
	},
	{
		name: 'name_karki',
		category: 'non volant',
		id: 'karki',
		price: 3200,
		neutedPrice: 1600,
		nameStat1: 'stat_weight',
		nameStat2: 'stat_stam',
		nameStat3: 'stat_dmg',
		nameStat4: 'stat_health'
	},
	{
		name: 'name_thorny',
		category: 'non volant',
		id: 'throny',
		price: 3200,
		neutedPrice: 1100,
		nameStat1: 'stat_dmg',
		nameStat2: 'stat_weight',
		nameStat3: '',
		nameStat4: ''
	},
	{
		name: 'name_maewing',
		category: 'non volant',
		id: 'maewing',
		price: 2600,
		neutedPrice: 1100,
		nameStat1: 'stat_weight',
		nameStat2: 'stat_stam',
		nameStat3: 'stat_dmg',
		nameStat4: 'stat_health'
	},
	{
		name: 'name_magma',
		category: 'non volant',
		id: 'magma',
		price: 9000,
		neutedPrice: 3200,
		nameStat1: 'stat_dmg',
		nameStat2: '',
		nameStat3: '',
		nameStat4: ''
	},
	{
		name: 'name_mammoth',
		category: 'non volant',
		id: 'mammoth',
		price: 3200,
		neutedPrice: 1100,
		nameStat1: 'stat_dmg',
		nameStat2: 'stat_weight',
		nameStat3: '',
		nameStat4: ''
	},
	{
		name: 'name_mana',
		category: 'volant',
		id: 'mana',
		price: 7800,
		neutedPrice: 2600,
		nameStat1: 'stat_dmg',
		nameStat2: 'stat_stam',
		nameStat3: 'stat_health',
		nameStat4: 'stat_weight'
	},
	{
		name: 'name_manta',
		category: 'non volant',
		id: 'manta',
		price: 3200,
		neutedPrice: 1300,
		nameStat1: 'stat_weight',
		nameStat2: 'stat_health',
		nameStat3: '',
		nameStat4: ''
	},
	{
		name: 'name_mantis',
		category: 'non volant',
		id: 'mantis',
		price: 9000,
		neutedPrice: 3200,
		nameStat1: 'stat_dmg',
		nameStat2: '',
		nameStat3: '',
		nameStat4: ''
	},
	{
		name: 'name_megaloceros',
		category: 'non volant',
		id: 'megaloceros',
		price: 3200,
		neutedPrice: 1100,
		nameStat1: 'stat_dmg',
		nameStat2: 'stat_weight',
		nameStat3: '',
		nameStat4: ''
	},
	{
		name: 'name_megalodon',
		category: 'non volant',
		id: 'megalodon',
		price: 4700,
		neutedPrice: 1600,
		nameStat1: 'stat_weight',
		nameStat2: 'stat_stam',
		nameStat3: 'stat_dmg',
		nameStat4: 'stat_health'
	},
	{
		name: 'name_megalosa',
		category: 'non volant',
		id: 'megalosa',
		price: 6300,
		neutedPrice: 2100,
		nameStat1: 'stat_dmg',
		nameStat2: 'stat_health',
		nameStat3: 'stat_stam',
		nameStat4: 'stat_weight'
	},
	{
		name: 'name_megath',
		category: 'non volant',
		id: 'megath',
		price: 6300,
		neutedPrice: 2100,
		nameStat1: 'stat_dmg',
		nameStat2: 'stat_health',
		nameStat3: 'stat_stam',
		nameStat4: 'stat_weight'
	},
	{
		name: 'name_mosa',
		category: 'non volant',
		id: 'mosa',
		price: 6300,
		neutedPrice: 2100,
		nameStat1: 'stat_dmg',
		nameStat2: 'stat_health',
		nameStat3: 'stat_stam',
		nameStat4: 'stat_weight'
	},
	{
		name: 'name_moschops',
		category: 'non volant',
		id: 'moschops',
		price: 3200,
		neutedPrice: 1100,
		nameStat1: 'stat_dmg',
		nameStat2: 'stat_weight',
		nameStat3: '',
		nameStat4: ''
	},
	{
		name: 'name_bear',
		category: 'non volant',
		id: 'bear',
		price: 4700,
		neutedPrice: 1600,
		nameStat1: 'stat_dmg',
		nameStat2: 'stat_weight',
		nameStat3: '',
		nameStat4: ''
	},
	{
		name: 'name_ovis',
		category: 'non volant',
		id: 'ovis',
		price: 3200,
		neutedPrice: 600,
		nameStat1: 'stat_health',
		nameStat2: '',
		nameStat3: '',
		nameStat4: ''
	},
	{
		name: 'name_phoenix',
		category: 'volant',
		id: 'phoenix',
		price: 3900,
		neutedPrice: 2100,
		nameStat1: 'stat_weight',
		nameStat2: 'stat_health',
		nameStat3: 'stat_dmg',
		nameStat4: ''
	},
	{
		name: 'name_proco',
		category: 'non volant',
		id: 'proco',
		price: 4700,
		neutedPrice: 1600,
		nameStat1: 'stat_dmg',
		nameStat2: 'stat_weight',
		nameStat3: '',
		nameStat4: ''
	},
	{
		name: 'name_ptera',
		category: 'volant',
		id: 'ptera',
		price: 1900,
		neutedPrice: 800,
		nameStat1: 'stat_weight',
		nameStat2: 'stat_stam',
		nameStat3: 'stat_dmg',
		nameStat4: 'stat_health'
	},
	{
		name: 'name_quetzal',
		category: 'volant',
		id: 'quetzal',
		price: 3200,
		neutedPrice: 1100,
		nameStat1: 'stat_weight',
		nameStat2: 'stat_stam',
		nameStat3: '',
		nameStat4: ''
	},
	{
		name: 'name_rollrat',
		category: 'non volant',
		id: 'rollrat',
		price: 6300,
		neutedPrice: 2100,
		nameStat1: 'stat_dmg',
		nameStat2: 'stat_weight',
		nameStat3: '',
		nameStat4: ''
	},
	{
		name: 'name_reaper',
		category: 'non volant',
		id: 'reaper',
		price: 9100,
		neutedPrice: 2600,
		nameStat1: 'stat_dmg',
		nameStat2: 'stat_health',
		nameStat3: 'stat_stam',
		nameStat4: 'stat_weight'
	},
	{
		name: 'name_rockdrake',
		category: 'non volant',
		id: 'rockdrake',
		price: 4700,
		neutedPrice: 1600,
		nameStat1: 'stat_weight',
		nameStat2: 'stat_stam',
		nameStat3: 'stat_dmg',
		nameStat4: 'stat_health'
	},
	{
		name: 'name_shadow',
		category: 'non volant',
		id: 'shadow',
		price: 11700,
		neutedPrice: 3900,
		nameStat1: 'stat_dmg',
		nameStat2: 'stat_health',
		nameStat3: 'stat_stam',
		nameStat4: 'stat_weight'
	},
	{
		name: 'name_sino',
		category: 'volant',
		id: 'sino',
		price: 2600,
		neutedPrice: 700,
		nameStat1: 'stat_stam',
		nameStat2: 'stat_weight',
		nameStat3: '',
		nameStat4: ''
	},
	{
		name: 'name_spino',
		category: 'non volant',
		id: 'spino',
		price: 4700,
		neutedPrice: 1600,
		nameStat1: 'stat_weight',
		nameStat2: 'stat_stam',
		nameStat3: 'stat_dmg',
		nameStat4: 'stat_health'
	},
	{
		name: 'name_stego',
		category: 'non volant',
		id: 'stego',
		price: 3200,
		neutedPrice: 1100,
		nameStat1: 'stat_health',
		nameStat2: 'stat_dmg',
		nameStat3: 'stat_stam',
		nameStat4: 'stat_weight'
	},
	{
		name: 'name_stryder',
		category: 'non volant TEK',
		id: 'stryder',
		price: 4000,
		neutedPrice: 4000,
		nameStat1: 'stat_charge',
		nameStat2: 'stat_weight',
		nameStat3: '',
		nameStat4: ''
	},
	{
		name: 'name_rex',
		category: 'non volant',
		id: 'rex',
		price: 9100,
		neutedPrice: 2600,
		nameStat1: 'stat_dmg',
		nameStat2: 'stat_health',
		nameStat3: 'stat_stam',
		nameStat4: 'stat_weight'
	},
	{
		name: 'name_terror',
		category: 'non volant',
		id: 'terror',
		price: 1900,
		neutedPrice: 800,
		nameStat1: 'stat_weight',
		nameStat2: 'stat_stam',
		nameStat3: 'stat_dmg',
		nameStat4: 'stat_health'
	},
	{
		name: 'name_theri',
		category: 'non volant',
		id: 'theri',
		price: 7800,
		neutedPrice: 2600,
		nameStat1: 'stat_dmg',
		nameStat2: 'stat_health',
		nameStat3: '',
		nameStat4: ''
	},
	{
		name: 'name_thyla',
		category: 'non volant',
		id: 'thyla',
		price: 3900,
		neutedPrice: 1300,
		nameStat1: 'stat_health',
		nameStat2: 'stat_stam',
		nameStat3: '',
		nameStat4: ''
	},
	{
		name: 'name_trike',
		category: 'non volant',
		id: 'trike',
		price: 3200,
		neutedPrice: 1100,
		nameStat1: 'stat_dmg',
		nameStat2: 'stat_weight',
		nameStat3: '',
		nameStat4: ''
	},
	{
		name: 'name_tropeo',
		category: 'volant',
		id: 'tropeo',
		price: 3200,
		neutedPrice: 1100,
		nameStat1: 'stat_health',
		nameStat2: 'stat_dmg',
		nameStat3: 'stat_stam',
		nameStat4: 'stat_weight'
	},
	{
		name: 'name_tuso',
		category: 'non volant',
		id: 'tuso',
		price: 7800,
		neutedPrice: 2600,
		nameStat1: 'stat_dmg',
		nameStat2: 'stat_health',
		nameStat3: '',
		nameStat4: ''
	},
	{
		name: 'name_unicorn',
		category: 'non volant',
		id: 'unicorn',
		price: 3200,
		neutedPrice: 1100,
		nameStat1: 'stat_health',
		nameStat2: 'stat_dmg',
		nameStat3: 'stat_stam',
		nameStat4: 'stat_weight'
	},
	{
		name: 'name_velo',
		category: 'non volant',
		id: 'velo',
		price: 9400,
		neutedPrice: 3900,
		nameStat1: 'stat_dmg',
		nameStat2: 'stat_stam',
		nameStat3: 'stat_health',
		nameStat4: 'stat_weight'
	},
	{
		name: 'name_rhino',
		category: 'non volant',
		id: 'rhino',
		price: 7800,
		neutedPrice: 3200,
		nameStat1: 'stat_dmg',
		nameStat2: 'stat_stam',
		nameStat3: 'stat_health',
		nameStat4: 'stat_weight'
	},
	{
		name: 'name_wyv',
		category: 'volant',
		id: 'wyv',
		price: 3900,
		neutedPrice: 1300,
		nameStat1: 'stat_dmg',
		nameStat2: 'stat_health',
		nameStat3: 'stat_stam',
		nameStat4: 'stat_weight'
	},
	{
		name: 'name_voidwyrm',
		category: 'volant',
		id: 'voidwyrm',
		price: 3900,
		neutedPrice: 1300,
		nameStat1: 'stat_dmg',
		nameStat2: 'stat_health',
		nameStat3: 'stat_stam',
		nameStat4: 'stat_weight'
	},
	{
		name: 'name_wyv_light',
		category: 'volant',
		id: 'wyv_light',
		price: 9400,
		neutedPrice: 3900,
		nameStat1: 'stat_dmg',
		nameStat2: 'stat_stam',
		nameStat3: 'stat_health',
		nameStat4: 'stat_weight'
	},
	{
		name: 'name_yuty',
		category: 'non volant',
		id: 'yuty',
		price: 3900,
		neutedPrice: 1300,
		nameStat1: 'stat_health',
		nameStat2: 'stat_stam',
		nameStat3: '',
		nameStat4: ''
	},
	{
		name: 'name_lumi',
		category: 'autre',
		id: 'lumi',
		price: 2400,
		neutedPrice: 800,
		nameStat1: 'stat_stam',
		nameStat2: 'stat_dmg',
		nameStat3: '',
		nameStat4: ''
	},
	{
		name: 'name_other',
		category: 'autre',
		id: 'other',
		price: 1600,
		neutedPrice: 600,
		nameStat1: 'stat_useful',
		nameStat2: '',
		nameStat3: '',
		nameStat4: ''
	}
]
